//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocGia
    {
        public DocGia()
        {
            this.PhieuMuons = new HashSet<PhieuMuon>();
        }
    
        public int MaDocGia { get; set; }
        public string HoTen { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public Nullable<int> MaLoaiThe { get; set; }
        public Nullable<int> MaKhoa { get; set; }
    
        public virtual Khoa Khoa { get; set; }
        public virtual LoaiTheThuVien LoaiTheThuVien { get; set; }
        public virtual ICollection<PhieuMuon> PhieuMuons { get; set; }
    }
}
