//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuMuon
    {
        public PhieuMuon()
        {
            this.ChiTietMuons = new HashSet<ChiTietMuon>();
        }
    
        public int MaPhieuMuon { get; set; }
        public System.DateTime NgayMuon { get; set; }
        public System.DateTime HanTra { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public bool TinhTrangTra { get; set; }
        public Nullable<int> MaDocGia { get; set; }
        public string MaThuThu { get; set; }
    
        public virtual ICollection<ChiTietMuon> ChiTietMuons { get; set; }
        public virtual DocGia DocGia { get; set; }
        public virtual ThuThu ThuThu { get; set; }
    }
}
