//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TacGia
    {
        public TacGia()
        {
            this.ThamGias = new HashSet<ThamGia>();
        }
    
        public int MaTacGia { get; set; }
        public string HoTen { get; set; }
    
        public virtual ICollection<ThamGia> ThamGias { get; set; }
    }
}
